# Generated by Django 5.2.1 on 2025-05-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_annually', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_products', models.IntegerField(blank=True, null=True)),
                ('max_orders_per_month', models.IntegerField(blank=True, null=True)),
                ('max_storage_gb', models.IntegerField(blank=True, null=True)),
                ('allow_custom_email_template', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
