# Generated by Django 5.2.1 on 2025-05-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_domain', models.CharField(max_length=255, unique=True)),
                ('shopify_access_token', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_id_external', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50, null=True)),
                ('current_billing_period_ends', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_product_count', models.IntegerField(default=0)),
                ('current_storage_used_bytes', models.BigIntegerField(default=0)),
                ('current_month_order_count', models.IntegerField(default=0)),
                ('last_order_count_reset_at', models.DateTimeField(blank=True, null=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
            ],
        ),
    ]
